exclude:
- /Bombic/android/.*
- /Bombic/app/.*
- /Bombic/desktop/.*
- /Bombic/gradle/.*
- /Bombic/html/.*
- /Bombic/ios/.*
component_depth: 1
languages:
- java

- name: java
 test:
  production:
    include:
       -  .*/Logic/.*\.java
    exclude:
      -  .*/Managers/.*\.java
      -  .*/Scenes/.*\.java
      -  .*/Screens/.*\.java
      -  .*/Tools/.*\.java
      -  .*/net/.*\.java
   
