exclude:
- /Bombic/android/.*
- /Bombic/app/.*
- /Bombic/desktop/.*
- /Bombic/gradle/.*
- /Bombic/html/.*
- /Bombic/ios/.*
component_depth: 1
languages:
- java
 test:
    exclude:
      - Bombic/core/src/com/lpoo/bombic/Managers/.*
      - Bombic/core/src/com/lpoo/bombic/Scenes/.*
      - Bombic/core/src/com/lpoo/bombic/Screens/.*
      - Bombic/core/src/com/lpoo/bombic/Tools/.*
      - Bombic/core/src/com/lpoo/bombic/net/.*
   
