exclude:
- /Bombic/android/.*
- /Bombic/app/.*
- /Bombic/desktop/.*
- /Bombic/gradle/.*
- /Bombic/html/.*
- /Bombic/ios/.*
component_depth: 1
languages:
- java
 test:
  
    exclude:
      - Bombic/core/src/com/lpoo/bombic/Managers/.*\.java
      - Bombic/core/src/com/lpoo/bombic/Scenes/.*\.java
      - Bombic/core/src/com/lpoo/bombic/Screens/.*\.java
      - Bombic/core/src/com/lpoo/bombic/Tools/.*\.java
      - Bombic/core/src/com/lpoo/bombic/net/.*\.java
   
